name: Events Demo 1
on:
  pull_request:
    types: # This is an activity type
      - opened
    branches: # This is a filter
      - main
      - 'dev-*' # This is all branches that starts with 'dev-' but no slashes, like dev-new, dev-this-is-new
      - 'feat/**' # All branches that starts with feat/ and any other word or slashes like feat/new, feat/new/button
  workflow_dispatch: # Don't forget the colon here in the end
  push:
    branches: # This is a filter
      - main
      - 'dev-*' # This is all branches that starts with 'dev-' but no slashes, like dev-new, dev-this-is-new
      - 'feat/**' # All branches that starts with feat/ and any other word or slashes like feat/new, feat/new/button
    paths-ignore: # This is a filter
      - '.github/workflows/*' # This will not trigger on push if at least one of the files changed was in the .github/workflows/ folder
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."